import type { Config } from 'tailwindcss';

export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'vsg-primary': 'var(--vsg-color-primary)',
                'vsg-action': 'var(--vsg-color-action)',
                'vsg-orange': {
                    50: 'var(--vsg-color-orange-50)',
                    100: 'var(--vsg-color-orange-100)',
                    200: 'var(--vsg-color-orange-200)',
                    300: 'var(--vsg-color-orange-300)',
                    400: 'var(--vsg-color-orange-400)',
                    500: 'var(--vsg-color-orange-500)',
                    600: 'var(--vsg-color-orange-600)',
                    700: 'var(--vsg-color-orange-700)',
                    800: 'var(--vsg-color-orange-800)',
                    900: 'var(--vsg-color-orange-900)',
                },
                'vsg-neutral': {
                    50: 'var(--vsg-color-neutral-50)',
                    100: 'var(--vsg-color-neutral-100)',
                    200: 'var(--vsg-color-neutral-200)',
                    300: 'var(--vsg-color-neutral-300)',
                    400: 'var(--vsg-color-neutral-400)',
                    500: 'var(--vsg-color-neutral-500)',
                    600: 'var(--vsg-color-neutral-600)',
                    700: 'var(--vsg-color-neutral-700)',
                    800: 'var(--vsg-color-neutral-800)',
                    900: 'var(--vsg-color-neutral-900)',
                    950: 'var(--vsg-color-neutral-950)',
                },
                'vsg-success': 'var(--vsg-color-success-500)',
                'vsg-warning': 'var(--vsg-color-warning-500)',
                'vsg-error': 'var(--vsg-color-error-500)',
                'vsg-info': 'var(--vsg-color-info-500)',
            },
            fontFamily: {
                sans: [
                    '-apple-system',
                    'BlinkMacSystemFont',
                    '"Segoe UI"',
                    'Roboto',
                    '"Helvetica Neue"',
                    'Arial',
                    'sans-serif',
                ],
                mono: [
                    '"SF Mono"',
                    'Monaco',
                    '"Cascadia Code"',
                    '"Roboto Mono"',
                    '"Courier New"',
                    'monospace',
                ],
            },
            spacing: {
                '0': 'var(--spacing-0)',
                '1': 'var(--spacing-1)',
                '2': 'var(--spacing-2)',
                '3': 'var(--spacing-3)',
                '4': 'var(--spacing-4)',
                '6': 'var(--spacing-6)',
                '8': 'var(--spacing-8)',
                '12': 'var(--spacing-12)',
                '16': 'var(--spacing-16)',
                '24': 'var(--spacing-24)',
                '32': 'var(--spacing-32)',
            },
            borderRadius: {
                'xs': 'var(--radius-xs)',
                'sm': 'var(--radius-sm)',
                'md': 'var(--radius-md)',
                'lg': 'var(--radius-lg)',
                'xl': 'var(--radius-xl)',
                'full': 'var(--radius-full)',
            },
            boxShadow: {
                'sm': 'var(--elevation-1)',
                'md': 'var(--elevation-2)',
                'lg': 'var(--elevation-3)',
                'xl': 'var(--elevation-4)',
                '2xl': 'var(--elevation-5)',
            },
        },
    },
    plugins: [],
} satisfies Config;
